//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.Validation", typeof(Validation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID must not be empty..
        /// </summary>
        public static string Category_Id_Required {
            get {
                return ResourceManager.GetString("Category_Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required..
        /// </summary>
        public static string Category_Name_Alphanumeric {
            get {
                return ResourceManager.GetString("Category_Name_Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name must be between 3 and 50 characters..
        /// </summary>
        public static string Category_Name_Length {
            get {
                return ResourceManager.GetString("Category_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name can only contain alphanumeric characters (no spaces or special characters)..
        /// </summary>
        public static string Category_Name_Required {
            get {
                return ResourceManager.GetString("Category_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchTerm must not exceed 50 characters..
        /// </summary>
        public static string Category_SearchTerm_Maximum {
            get {
                return ResourceManager.GetString("Category_SearchTerm_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchTerm must be at least 2 characters long when provided..
        /// </summary>
        public static string Category_SearchTerm_Minimum {
            get {
                return ResourceManager.GetString("Category_SearchTerm_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category IDs cannot be empty GUIDs..
        /// </summary>
        public static string Product_Category_Empty {
            get {
                return ResourceManager.GetString("Product_Category_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one category must be assigned..
        /// </summary>
        public static string Product_Category_Missing {
            get {
                return ResourceManager.GetString("Product_Category_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID must not be empty..
        /// </summary>
        public static string Product_Id_Required {
            get {
                return ResourceManager.GetString("Product_Id_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string Product_Name_Alphanumeric {
            get {
                return ResourceManager.GetString("Product_Name_Alphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name must be between 3 and 50 characters..
        /// </summary>
        public static string Product_Name_Length {
            get {
                return ResourceManager.GetString("Product_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string Product_Name_Required {
            get {
                return ResourceManager.GetString("Product_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero..
        /// </summary>
        public static string Product_Price_GreaterThan {
            get {
                return ResourceManager.GetString("Product_Price_GreaterThan", resourceCulture);
            }
        }
    }
}
