/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProductDtoFromDiscriminatorValue, type ProductDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /products/{id}
 */
export interface ProductsItemRequestBuilder extends BaseRequestBuilder<ProductsItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ProductDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ProductDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProductsItemRequestBuilderUriTemplate = "{+baseurl}/products/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProductsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProductsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createProductDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
