receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: 0.0.0.0:9090
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true # Wenn du keine TLS-Zertifikate verwendest
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100

  attributes:
    actions:
      - key: service.name
        action: insert
        value: minimal-api

  batch:
    timeout: 1s
    send_batch_size: 512

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    logs:
      receivers: [otlp]
      processors: [attributes] 
      exporters: [loki]
    traces:
      receivers: [otlp]
      processors: [attributes, batch] 
      exporters: [otlp/jaeger, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [attributes, batch] 
      exporters: [prometheus]
