# YarpURL
@baseUrl = http://localhost:5062 
# ApiURL
# @baseUrl = https://localhost:5044

# Example Product ID for GET, PUT, DELETE
@productId = 0198411a-af04-7676-add0-4a8743334d77
# Example Category ID for GET, PUT, DELETE
@categoryId = 0198411a-aee8-770b-9a62-c07b54f45b02

###
### PRODUCTS API ENDPOINTS
###
###
# @name GetAllProducts
GET {{baseUrl}}/products?PageNumber=1&PageSize=5&OrderBy=Price&Ascending=true
Accept: application/json

###
# @name CreateProduct
POST {{baseUrl}}/products
Content-Type: application/json
{
  "name": "SuperMegaProduct",
  "price": 99.99,
  "description": "A very detailed description of the super mega product.",
  "categoryIds": [
    "{{categoryId}}"
  ]
}

###
# @name CreateProduct 
# Invalid CategoryId
POST {{baseUrl}}/products
Content-Type: application/json
{
  "name": "SuperMegaProduct",
  "price": 99.99,
  "description": "A very detailed description of the super mega product.",
  "categoryIds": [
    "00000000-0000-0000-0000-000000000000"
  ]
}

###
# @name GetAllProducts
GET {{baseUrl}}/products?SearchTerm=test&PageNumber=1&PageSize=5
Accept: application/json

###
# @name GetProductById
GET {{baseUrl}}/products/{{productId}}
Accept: application/json

###
# @name UpdateProduct
PUT {{baseUrl}}/products
Content-Type: application/json
{
  "id": "{{productId}}",
  "name": "UpdatedProductName",
  "price": 123.45,
  "description": "An updated description.",
  "categoryIds": [
    "{{categoryId}}"
  ]
}

###
# @name DeleteProduct
DELETE {{baseUrl}}/products
Content-Type: application/json
{
  "id": "{{productId}}"
}

###
### CATEGORIES API ENDPOINTS
###

###
# @name GetAllCategories
GET {{baseUrl}}/categories
Accept: application/json

###
# @name CreateCategory
POST {{baseUrl}}/categories
Content-Type: application/json
{
  "name": "Electronics"
}

###
# @name GetAllCategories
GET {{baseUrl}}/categories?SearchTerm=test
Accept: application/json

###
# @name GetCategoryById
GET {{baseUrl}}/categories/{{categoryId}}
Accept: application/json

###
# @name UpdateCategory
PUT {{baseUrl}}/categories
Content-Type: application/json
{
  "id": "{{categoryId}}",
  "name": "Books & Media"
}

###
# @name DeleteCategory
DELETE {{baseUrl}}/categories
Content-Type: application/json
{
  "id": "{{categoryId}}"
}