/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCategoryDtoFromDiscriminatorValue, type CategoryDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /categories/{id}
 */
export interface CategoriesItemRequestBuilder extends BaseRequestBuilder<CategoriesItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CategoryDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CategoryDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CategoriesItemRequestBuilderUriTemplate = "{+baseurl}/categories/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CategoriesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CategoriesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCategoryDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
